# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Pick your own package manager and build script
      - name: Install node_modules
        run: npm install
      - name: Build Nuxt.js
        run: npx nuxt build --preset github_pages
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          VUE_APP_CV_LINK: ${{ secrets.VUE_APP_CV_LINK }}
          VUE_APP_DEFAULT_LOCALE: ${{ secrets.VUE_APP_DEFAULT_LOCALE }}
          VUE_APP_DOMAIN: ${{ secrets.VUE_APP_DOMAIN }}
          VUE_APP_EMAILJS_PUBLIC_KEY: ${{ secrets.VUE_APP_EMAILJS_PUBLIC_KEY }}
          VUE_APP_EMAILJS_SERVICE: ${{ secrets.VUE_APP_EMAILJS_SERVICE }}
          VUE_APP_EMAILJS_TEMPLATE: ${{ secrets.VUE_APP_EMAILJS_TEMPLATE }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public
  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
